smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -367,43 +367,84 @@ jobs:
             ansible-playbook -i inventory.txt deploy-backend.yml
       - destroy-environment
       - revert-migrations
-#    smoke-test:
-#     docker:
-#       # Lightweight Docker image 
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Get backend url
-#           command: |
-#             # your code here
-#       - run:
-#           name: Backend smoke test.
-#           command: |
-#             # your code here
-#       - run:
-#           name: Frontend smoke test.
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+  smoke-test:
+   docker:
+     # Lightweight Docker image
+      - image: cimg/base:stable
+   steps:
+     # Checkout code from git
+     - checkout
+     - install_nodejs
+     - install_awscli
+     - run:
+         name: Get backend url
+         command: |
+           BACKEND_IP=$(aws ec2 describe-instances \
+             --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+             --query "Reservations[*].Instances[*].PublicIpAddress" \
+             --output text)
+           export API_URL=http://${BACKEND_IP}:3030
+           echo ${BACKEND_IP}
+           echo ${API_URL}
+           echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+           
+           if curl -s $API_URL/api/status grep "ok"
+           then
+             exit 0
+           else
+             exit 1
+           fi
+     - run:
+         name: Frontend smoke test
+         command: |
+            FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com
+           echo ${FRONTEND_WEBSITE}
+           if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+           then
+             exit 0
+           else
+             exit 1
+           fi
+     - destroy-environment
+     - revert-migrations
+     - run:
+         name: Backend smoke test.
+         command: |
+           # your code here
+     - run:
+         name: Frontend smoke test.
+         command: |
+           # your code here
+     # Here's where you will add some code to rollback on failure
 
-#   cloudfront-update:
-#     docker:
-#       # Docker image here that supports AWS CLI
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Install dependencies
-#           command: |
-#             # your code here
-#       - run:
-#           name: Update cloudfront distribution
-#           command: |
-#             # your code here
-#       # Here's where you will add some code to rollback on failure  
+   cloudfront-update:
+     docker:
+       - image: amazon/aws-cli
+       # Docker image here that supports AWS CLI
+     steps:
+       # Checkout code from git
+       - checkout
+       - run:
+           name: Install dep and save Old Workflow ID to kvdb
+           command: |
+             export OLD_WORKFLOW_ID=$(aws cloudformation \
+             list exports \
+             --query "Exports[?Name==\`WorkflowID\`].Value" \
+             --no-paginate \
+             --output text)
+             echo "Old Workflow ID: ${OLD_WORKFLOW_ID}"
+             curl https://kvdb.io/YKNUhWcQ84k2dvnGArNnHk/old_workflow_id -d "&{OLD_WORKFLOW_ID}"
+             # your code here
+       - run:
+           name: Update cloudfront distribution
+           command: |
+             aws cloudformation deploy \
+                --template-file .circleci/files/cloudfront.yml \
+                --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7} \
+                --stack-name InitialStack
+       - destroy-environment
+       - revert-migrations
+       # Here's where you will add some code to rollback on failure
 
 # cleanup:
 #     docker:
@@ -451,9 +492,9 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      # - smoke-test:
-      #     requires: [deploy-backend, deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test]
+      - smoke-test:
+         requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+         requires: [smoke-test]
       # - cleanup:
       #     requires: [cloudfront-update]
