format

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,7 +10,7 @@ commands:
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
-
+  
   install_ansible:
     description: Install ansible
     steps:
@@ -43,13 +43,13 @@ commands:
             aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
             aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
             aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
-
+  
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
       workflow_id:
-          default: ${CIRCLE_WORKFLOW_ID:0:7}
-          type: string
+        default: ${CIRCLE_WORKFLOW_ID:0:7}
+        type: string
     steps:
       - run:
           name: Revert migrations
@@ -63,7 +63,7 @@ commands:
               npm install
               npm run migration:revert
             fi
-            
+
 jobs:
   build-frontend:
     docker:
@@ -71,7 +71,7 @@ jobs:
     steps:
       - checkout
       - restore_cache:
-          keys: [frontend-build]
+          keys: [ frontend-build ]
       - run:
           name: Build front-end
           command: |
@@ -79,16 +79,16 @@ jobs:
             npm install
             npm run build
       - save_cache:
-          paths: [frontend/node_modules]
+          paths: [ frontend/node_modules ]
           key: frontend-build
-
+  
   build-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [backend-build]
+          keys: [ backend-build ]
       - run:
           name: Back-end build
           command: |
@@ -96,9 +96,9 @@ jobs:
             npm install
             npm run build
       - save_cache:
-          paths: [backend/node_modules]
+          paths: [ backend/node_modules ]
           key: backend-build
-
+  
   test-frontend:
     docker:
       # Docker image here
@@ -108,9 +108,9 @@ jobs:
       - checkout
       # Restore from cache
       - restore_cache:
-          keys: [frontend-test]
+          keys: [ frontend-test ]
       # Your job code here
-
+      
       - run:
           name: test front-end
           command: |
@@ -118,22 +118,22 @@ jobs:
             npm install
             npm run test
       - save_cache:
-          paths: [frontend/node_modules]
+          paths: [ frontend/node_modules ]
           key: frontend-test
-
-                
+  
+  
   test-backend:
     docker:
       # Docker image here
       - image: circleci/node:13.8.0
-
+    
     steps:
       # Checkout code from git
       - checkout
-
+      
       # Restore from cache
       - restore_cache:
-          keys: [backend-test]
+          keys: [ backend-test ]
       # Your job code here
       - run:
           name: test back-end
@@ -142,21 +142,21 @@ jobs:
             npm install
             npm run test
       - save_cache:
-          paths: [backend/node_modules]
+          paths: [ backend/node_modules ]
           key: backend-test
-            
+  
   scan-frontend:
     docker:
       # Docker image here
       - image: circleci/node:13.8.0
-
+    
     steps:
       # Checkout code from git
       - checkout
-
+      
       # Restore from cache
       - restore_cache:
-          keys: [scan-frontend]
+          keys: [ scan-frontend ]
       # Your job code here
       - run:
           name: scan front-end
@@ -168,21 +168,21 @@ jobs:
             npm audit --audit-level=critical
             npm audit fix
       - save_cache:
-          paths: [frontend/node_modules]
+          paths: [ frontend/node_modules ]
           key: scan-frontend
-
-
+  
+  
   scan-backend:
     docker:
       # Docker image here
       - image: circleci/node:13.8.0
-
+    
     steps:
       # Checkout code from git
       - checkout
       # Restore from cache
       - restore_cache:
-          keys: [scan-backend]
+          keys: [ scan-backend ]
       # Your job code here
       - run:
           name: scan back-end
@@ -191,9 +191,9 @@ jobs:
             npm install
             npm audit fix --audit-level=critical --force
       - save_cache:
-          paths: [backend/node_modules]
+          paths: [ backend/node_modules ]
           key: scan-backend
-
+  
   deploy-infrastructure:
     docker:
       # Docker image here that supports AWS CLI
@@ -235,37 +235,37 @@ jobs:
           paths:
             - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure      
-
+  
   configure-infrastructure:
     docker:
-     # Docker image here that supports Ansible
+      # Docker image here that supports Ansible
       - image: cimg/base:stable
     steps:
-     # Checkout code from git
-     - checkout
-     # Add ssh keys with fingerprint
-     - add_ssh_keys:
-        fingerprints:
-          - "3a:a3:18:3b:87:49:9a:70:fd:0e:91:d7:ad:de:f2:6e"
-     # attach workspace
-     - attach_workspace:
-        at: ~/
-
-     - install_ansible
-
-     - run:
-         name: Configure server
-         command: |
-           cd .circleci/ansible
-           cat inventory.txt           
-           ansible-playbook -i inventory.txt configure-server.yml
-     - destroy-environment
-   # Here's where you will add some code to rollback on failure
-
+      # Checkout code from git
+      - checkout
+      # Add ssh keys with fingerprint
+      - add_ssh_keys:
+          fingerprints:
+            - "3a:a3:18:3b:87:49:9a:70:fd:0e:91:d7:ad:de:f2:6e"
+      # attach workspace
+      - attach_workspace:
+          at: ~/
+      
+      - install_ansible
+      
+      - run:
+          name: Configure server
+          command: |
+            cd .circleci/ansible
+            cat inventory.txt
+            ansible-playbook -i inventory.txt configure-server.yml
+      - destroy-environment
+    # Here's where you will add some code to rollback on failure
+  
   run-migrations:
     docker:
-     # Docker image here that supports NodeJS
-     - image: circleci/node:13.8.0
+      # Docker image here that supports NodeJS
+      - image: circleci/node:13.8.0
     steps:
       - checkout
       - install_awscli
@@ -286,7 +286,7 @@ jobs:
             fi
       - destroy-environment
       - revert-migrations
-
+  
   deploy-frontend:
     docker:
       # Docker image here that supports Ansible
@@ -314,7 +314,7 @@ jobs:
             echo "API_URL=${API_URL}"
             echo API_URL="http://$BACKEND_URL:3030" >> frontend/.env
             cat frontend/.env
-
+      
       - run:
           name: Deploy frontend
           command: |
@@ -326,9 +326,9 @@ jobs:
             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
       - destroy-environment
       - revert-migrations
-
-     # Here's where you will add some code to rollback on failure
-                    
+        
+        # Here's where you will add some code to rollback on failure
+  
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
@@ -350,112 +350,112 @@ jobs:
             cd backend
             npm install
       - run:
-          name: Deploy backend
-          command: |
-            cd backend
-            npm i 
-            npm run build
-            cd ..
-            cd .circleci/ansible
-            mkdir files
-            cd files
-            tar -C ../../../backend -czvf artifact.tar.gz .
-            cd ../
-            
-            echo "inventory file contents ---"
-            cat inventory.txt
-            ansible-playbook -i inventory.txt deploy-backend.yml
+        name: Deploy backend
+        command: |
+          cd backend
+          npm i
+          npm run build
+          cd ..
+          cd .circleci/ansible
+          mkdir files
+          cd files
+          tar -C ../../../backend -czvf artifact.tar.gz .
+          cd ../
+        
+          echo "inventory file contents ---"
+          cat inventory.txt
+          ansible-playbook -i inventory.txt deploy-backend.yml
       - destroy-environment
       - revert-migrations
   smoke-test:
     docker:
-     # Lightweight Docker image
+      # Lightweight Docker image
       - image: cimg/base:stable
     steps:
-     # Checkout code from git
-     - checkout
-     - install_nodejs
-     - install_awscli
-     - run:
-         name: Get backend url
-         command: |
-           BACKEND_IP=$(aws ec2 describe-instances \
-             --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
-             --query "Reservations[*].Instances[*].PublicIpAddress" \
-             --output text)
-           export API_URL=http://${BACKEND_IP}:3030
-           echo ${BACKEND_IP}
-           echo ${API_URL}
-           echo backend-${CIRCLE_WORKFLOW_ID:0:7}
-           
-           if curl -s $API_URL/api/status grep "ok"
-             then
-               exit 0
-           else
-             exit 1
-           fi
-     - run:
-       name: Frontend smoke test
-       command: |
-         FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com
-         echo ${FRONTEND_WEBSITE}
-         if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-           then
-             exit 0
-         else
-           exit 1
-         fi
-     - destroy-environment
-     - revert-migrations
-
+      # Checkout code from git
+      - checkout
+      - install_nodejs
+      - install_awscli
+      - run:
+        name: Get backend url
+        command: |
+          BACKEND_IP=$(aws ec2 describe-instances \
+            --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            --query "Reservations[*].Instances[*].PublicIpAddress" \
+            --output text)
+          export API_URL=http://${BACKEND_IP}:3030
+          echo ${BACKEND_IP}
+          echo ${API_URL}
+          echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+        
+          if curl -s $API_URL/api/status grep "ok"
+            then
+              exit 0
+          else
+            exit 1
+          fi
+      - run:
+        name: Frontend smoke test
+        command: |
+          FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com
+          echo ${FRONTEND_WEBSITE}
+          if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+            then
+              exit 0
+          else
+            exit 1
+          fi
+      - destroy-environment
+      - revert-migrations
+  
   cloudfront-update:
     docker:
-     - image: amazon/aws-cli
-     # Docker image here that supports AWS CLI
+      - image: amazon/aws-cli
+      # Docker image here that supports AWS CLI
     steps:
-     # Checkout code from git
-     - checkout
-     - run:
-         name: Install dep and save Old Workflow ID to kvdb
-         command: |
-           export OLD_WORKFLOW_ID=$(aws cloudformation \
-           list exports \
-           --query "Exports[?Name==\`WorkflowID\`].Value" \
-           --no-paginate \
-           --output text)
-           echo "Old Workflow ID: ${OLD_WORKFLOW_ID}"
-           curl https://kvdb.io/YKNUhWcQ84k2dvnGArNnHk/old_workflow_id -d "&{OLD_WORKFLOW_ID}"
-           # your code here
-     - run:
-         name: Update cloudfront distribution
-         command: |
-           aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7} \
-              --stack-name InitialStack
-     - destroy-environment
-     - revert-migrations
-     # Here's where you will add some code to rollback on failure
+      # Checkout code from git
+      - checkout
+      - run:
+        name: Install dep and save Old Workflow ID to kvdb
+        command: |
+          export OLD_WORKFLOW_ID=$(aws cloudformation \
+          list exports \
+          --query "Exports[?Name==\`WorkflowID\`].Value" \
+          --no-paginate \
+          --output text)
+          echo "Old Workflow ID: ${OLD_WORKFLOW_ID}"
+          curl https://kvdb.io/YKNUhWcQ84k2dvnGArNnHk/old_workflow_id -d "&{OLD_WORKFLOW_ID}"
+          # your code here
+      - run:
+        name: Update cloudfront distribution
+        command: |
+          aws cloudformation deploy \
+             --template-file .circleci/files/cloudfront.yml \
+             --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7} \
+             --stack-name InitialStack
+      - destroy-environment
+      - revert-migrations
+  # Here's where you will add some code to rollback on failure
+  
+  # cleanup:
+  #     docker:
+  #       # Docker image here
+  #     steps:
+  #       # Checkout code from git
+  #       - run:
+  #           name: Get old stack workflow id
+  #           command: |
+  #             # your code here
+  #             export OldWorkflowID="the id here"
+  #             export STACKS=[] #put the list of stacks here
+  #       - run:
+  #           name: Remove old stacks and files
+  #           command: |
+  #             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+  #             then
+  #               # your code here
+  #             fi
 
-# cleanup:
-#     docker:
-#       # Docker image here
-#     steps:
-#       # Checkout code from git
-#       - run:
-#           name: Get old stack workflow id
-#           command: |
-#             # your code here
-#             export OldWorkflowID="the id here"
-#             export STACKS=[] #put the list of stacks here
-#       - run:
-#           name: Remove old stacks and files
-#           command: |
-#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-#             then
-#               # your code here
-#             fi
-            
 
 workflows:
   default:
@@ -463,29 +463,29 @@ workflows:
       - build-frontend
       - build-backend
       - test-frontend:
-          requires: [build-frontend]
+          requires: [ build-frontend ]
       - test-backend:
-          requires: [build-backend]
+          requires: [ build-backend ]
       - scan-backend:
-          requires: [build-backend]
+          requires: [ build-backend ]
       - scan-frontend:
-          requires: [build-frontend]
+          requires: [ build-frontend ]
       - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+          requires: [ test-frontend, test-backend, scan-frontend, scan-backend ]
           filters:
             branches:
-              only: [john/auto-deploy]
+              only: [ john/auto-deploy ]
       - configure-infrastructure:
-          requires: [deploy-infrastructure]
+          requires: [ deploy-infrastructure ]
       - run-migrations:
-          requires: [configure-infrastructure]
+          requires: [ configure-infrastructure ]
       - deploy-frontend:
-          requires: [run-migrations]
+          requires: [ run-migrations ]
       - deploy-backend:
-          requires: [run-migrations]
+          requires: [ run-migrations ]
       - smoke-test:
-         requires: [deploy-backend, deploy-frontend]
+          requires: [ deploy-backend, deploy-frontend ]
       - cloudfront-update:
-         requires: [smoke-test]
+          requires: [ smoke-test ]
       # - cleanup:
       #     requires: [cloudfront-update]
