format

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -368,10 +368,10 @@ jobs:
       - destroy-environment
       - revert-migrations
   smoke-test:
-   docker:
+    docker:
      # Lightweight Docker image
       - image: cimg/base:stable
-   steps:
+    steps:
      # Checkout code from git
      - checkout
      - install_nodejs
@@ -395,47 +395,47 @@ jobs:
              exit 1
            fi
      - run:
-         name: Frontend smoke test
-         command: |
-           FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com
-           echo ${FRONTEND_WEBSITE}
-           if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-           then
-             exit 0
-           else
-             exit 1
-           fi
+       name: Frontend smoke test
+       command: |
+         FRONTEND_WEBSITE=http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-2.amazonaws.com
+         echo ${FRONTEND_WEBSITE}
+         if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+         then
+           exit 0
+         else
+           exit 1
+         fi
      - destroy-environment
      - revert-migrations
 
-   cloudfront-update:
-     docker:
-       - image: amazon/aws-cli
-       # Docker image here that supports AWS CLI
-     steps:
-       # Checkout code from git
-       - checkout
-       - run:
-           name: Install dep and save Old Workflow ID to kvdb
-           command: |
-             export OLD_WORKFLOW_ID=$(aws cloudformation \
-             list exports \
-             --query "Exports[?Name==\`WorkflowID\`].Value" \
-             --no-paginate \
-             --output text)
-             echo "Old Workflow ID: ${OLD_WORKFLOW_ID}"
-             curl https://kvdb.io/YKNUhWcQ84k2dvnGArNnHk/old_workflow_id -d "&{OLD_WORKFLOW_ID}"
-             # your code here
-       - run:
-           name: Update cloudfront distribution
-           command: |
-             aws cloudformation deploy \
-                --template-file .circleci/files/cloudfront.yml \
-                --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7} \
-                --stack-name InitialStack
-       - destroy-environment
-       - revert-migrations
-       # Here's where you will add some code to rollback on failure
+  cloudfront-update:
+    docker:
+     - image: amazon/aws-cli
+     # Docker image here that supports AWS CLI
+    steps:
+     # Checkout code from git
+     - checkout
+     - run:
+         name: Install dep and save Old Workflow ID to kvdb
+         command: |
+           export OLD_WORKFLOW_ID=$(aws cloudformation \
+           list exports \
+           --query "Exports[?Name==\`WorkflowID\`].Value" \
+           --no-paginate \
+           --output text)
+           echo "Old Workflow ID: ${OLD_WORKFLOW_ID}"
+           curl https://kvdb.io/YKNUhWcQ84k2dvnGArNnHk/old_workflow_id -d "&{OLD_WORKFLOW_ID}"
+           # your code here
+     - run:
+         name: Update cloudfront distribution
+         command: |
+           aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --parameter-overrides WorkflowID=${CIRCLE_WORKFLOW_ID:0:7} \
+              --stack-name InitialStack
+     - destroy-environment
+     - revert-migrations
+     # Here's where you will add some code to rollback on failure
 
 # cleanup:
 #     docker:
